= JSON threat protection policy

ifdef::env-github[]
image:https://ci.gravitee.io/buildStatus/icon?job=gravitee-io/gravitee-policy-json-threat-protection/master["Build status", link="https://ci.gravitee.io/job/gravitee-io/job/gravitee-policy-json-threat-protection/"]
image:https://badges.gitter.im/Join Chat.svg["Gitter", link="https://gitter.im/gravitee-io/gravitee-io?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
endif::[]

== Phase

[cols="2*", options="header"]
|===
^|onRequest
^|onRequestContent
^.^|
^.^| X

|===

== Description

You can use the `json-threat-protection` policy to validate a JSON request body by specifying limits for various JSON structures (such as arrays, field names and string values).
When an invalid request is detected (meaning the limit is reached), the request will be considered a threat and rejected with a `400 BAD REQUEST`.

== Configuration

|===
|Property |Required |Description |Type| Default

.^|maxEntries
^.^|
|Maximum number of entries allowed for a JSON object. Example: In ```{ "a":{ "b":1, "c":2, "d":3 }}```, ```a``` has 3 entries
^.^|integer (-1 to specify no limit)
|100

.^|maxArraySize
^.^|
|Maximum number of elements allowed in an array
^.^|integer (-1 to specify no limit)
|100

.^|maxDepth
^.^|
|Maximum depth of JSON structure. Example: ```{ "a":{ "b":{ "c":true }}}``` has a depth of 3.
^.^|integer (-1 to specify no limit)
|100

.^|maxNameLength
^.^|
|Maximum string length allowed for a JSON property name
^.^|integer (-1 to specify no limit)
|100

.^|maxValueLength
^.^|
|Maximum string length allowed for a JSON property value
^.^|integer (-1 to specify no limit)
|500

|===

== Errors

=== HTTP status code

|===
|Code |Message

.^| ```400```

a| Received in the following cases:

* Invalid JSON structure
* Maximum depth exceeded
* Maximum JSON entries exceeded
* Maximum JSON array size exceeded
* Maximum JSON field name length exceeded
* Maximum JSON field value length exceeded

|===

You can override the default response provided by the policy with the response templates feature. These templates must be defined at API level (see the API Console *Response Templates* option in the API *Proxy* menu).

The error keys sent by this policy are as follows:

[cols="2*", options="header"]
|===
^|Key
^|Parameters

.^|JSON_THREAT_DETECTED
^.^|-

.^|JSON_THREAT_MAX_DEPTH
^.^|-

.^|JSON_THREAT_MAX_ENTRIES
^.^|-

.^|JSON_THREAT_MAX_NAME_LENGTH
^.^|-

.^|JSON_THREAT_MAX_VALUE_LENGTH
^.^|-

.^|JSON_MAX_ARRAY_SIZE
^.^|-

|===
